name: Docs
on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 3

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "10"

      - run: node --version
      - run: npm --version
      - run: java -version

      - name: Install npm dependencies
        run: npm ci
        env:
          CI: true

      - name: Test docs
        run: npm run docs
